include:
  - docker-compose.yml

services:
  monitor-server:
    image: bitnami/node:latest
    container_name: monitor-server
    ports:
      - '8081:8081'
    volumes:
      - ../:/app/monitor
    working_dir: /app/monitor/apps/backend/monitor
    command: node dist/main.js
    depends_on:
      - monitor-clickhouse
      - monitor-postgres
    environment:
      - NODE_ENV=production
  monitor-caddy:
    image: caddy:latest
    container_name: monitor-caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy:/etc/caddy
      - ../apps/frontend/monitor/dist:/app/frontend/monitor/dist
